// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/target/calculate": {
            "post": {
                "description": "根据人群特征、营养素名称和场景，计算目标中位数并检查P95是否超UL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "营养素目标计算"
                ],
                "summary": "计算营养素目标摄入量",
                "parameters": [
                    {
                        "description": "计算请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CalculateTargetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回计算结果",
                        "schema": {
                            "$ref": "#/definitions/dto.CalculateTargetResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CalculateTargetRequest": {
            "type": "object",
            "required": [
                "age",
                "crowd",
                "gender",
                "nutrient_name",
                "scenario"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "maximum": 120,
                    "minimum": 0,
                    "example": 30
                },
                "crowd": {
                    "type": "string",
                    "example": "普通人群"
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "男",
                        "女"
                    ],
                    "example": "男"
                },
                "nutrient_name": {
                    "type": "string",
                    "example": "维生素C"
                },
                "scenario": {
                    "type": "string",
                    "enum": [
                        "A",
                        "B",
                        "C"
                    ],
                    "example": "A"
                }
            }
        },
        "dto.CalculateTargetResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.TargetData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.TargetData": {
            "type": "object",
            "properties": {
                "adjustment_factor": {
                    "description": "调整因子",
                    "type": "number"
                },
                "exceed_ul": {
                    "description": "是否超过UL",
                    "type": "boolean"
                },
                "nutrient_name": {
                    "type": "string"
                },
                "original_cv": {
                    "description": "原始变异系数",
                    "type": "number"
                },
                "original_mean": {
                    "description": "原始平均摄入量",
                    "type": "number"
                },
                "target_median": {
                    "description": "目标中位数",
                    "type": "number"
                },
                "target_p95": {
                    "description": "目标P95值",
                    "type": "number"
                },
                "ul": {
                    "description": "UL值",
                    "type": "number"
                },
                "unit": {
                    "description": "单位",
                    "type": "string"
                },
                "warning": {
                    "description": "警告信息",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "营养素目标计算器API",
	Description:      "基于数据库摄入数据和DRIs计算营养素目标摄入量的API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
