// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/target/calculate": {
            "post": {
                "description": "根据人群特征、营养素名称和场景，计算目标中位数并检查P95是否超UL，结果自动保存到Redis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "营养素目标计算"
                ],
                "summary": "计算营养素目标摄入量",
                "parameters": [
                    {
                        "description": "计算请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CalculateTargetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回计算结果，包含version_id用于后续查询和对比",
                        "schema": {
                            "$ref": "#/definitions/dto.CalculateTargetResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/target/compare": {
            "post": {
                "description": "对比两个计算版本的参数和结果差异，生成详细的对比报告",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本对比"
                ],
                "summary": "对比两个历史版本差异",
                "parameters": [
                    {
                        "description": "对比请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CompareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回对比结果，包含详细的差异分析",
                        "schema": {
                            "$ref": "#/definitions/dto.CompareResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    },
                    "404": {
                        "description": "某个版本不存在或已过期",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/target/history": {
            "get": {
                "description": "分页获取计算历史记录，可通过user_id过滤特定用户的记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "历史记录管理"
                ],
                "summary": "获取计算历史记录列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID，可选，不填则返回所有记录",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页条数，默认10",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回历史记录列表",
                        "schema": {
                            "$ref": "#/definitions/dto.HistoryListResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/target/history/{version_id}": {
            "get": {
                "description": "根据version_id获取计算结果的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "历史记录管理"
                ],
                "summary": "获取历史记录详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "计算结果版本ID",
                        "name": "version_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回历史记录详情",
                        "schema": {
                            "$ref": "#/definitions/dto.HistoryDetailResponse"
                        }
                    },
                    "404": {
                        "description": "记录不存在或已过期",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CalculateTargetRequest": {
            "type": "object",
            "required": [
                "age",
                "crowd",
                "gender",
                "nutrient_name",
                "scenario"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "maximum": 120,
                    "minimum": 0,
                    "example": 30
                },
                "crowd": {
                    "type": "string",
                    "example": "普通人群"
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "男",
                        "女"
                    ],
                    "example": "男"
                },
                "nutrient_name": {
                    "type": "string",
                    "example": "维生素C"
                },
                "scenario": {
                    "type": "string",
                    "enum": [
                        "A",
                        "B",
                        "C"
                    ],
                    "example": "A"
                },
                "user_id": {
                    "description": "可选用户标识，用于关联历史记录",
                    "type": "string",
                    "example": "user_123"
                }
            }
        },
        "dto.CalculateTargetResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.TargetData"
                },
                "message": {
                    "type": "string"
                },
                "version_id": {
                    "description": "计算结果的版本ID（用于后续查询和对比）",
                    "type": "string"
                }
            }
        },
        "dto.CalculationResult": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "计算时间",
                    "type": "string"
                },
                "expire_at": {
                    "description": "过期时间",
                    "type": "string"
                },
                "request": {
                    "description": "原始请求参数",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.CalculateTargetRequest"
                        }
                    ]
                },
                "result": {
                    "description": "计算结果",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.TargetData"
                        }
                    ]
                },
                "version_id": {
                    "description": "唯一版本ID",
                    "type": "string"
                }
            }
        },
        "dto.CommonResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.CompareDiffItem": {
            "type": "object",
            "properties": {
                "change_type": {
                    "description": "变化类型：increase/decrease/no_change/different",
                    "type": "string"
                },
                "description": {
                    "description": "字段描述",
                    "type": "string"
                },
                "diff": {
                    "description": "差异值（数值型）",
                    "type": "number"
                },
                "diff_percent": {
                    "description": "差异百分比（数值型）",
                    "type": "string"
                },
                "field": {
                    "description": "字段名",
                    "type": "string"
                },
                "value1": {
                    "description": "版本1的值"
                },
                "value2": {
                    "description": "版本2的值"
                }
            }
        },
        "dto.CompareRequest": {
            "type": "object",
            "required": [
                "version_id1",
                "version_id2"
            ],
            "properties": {
                "version_id1": {
                    "type": "string",
                    "example": "calc_abc123"
                },
                "version_id2": {
                    "type": "string",
                    "example": "calc_def456"
                }
            }
        },
        "dto.CompareResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "diff_summary": {
                    "$ref": "#/definitions/dto.CompareSummary"
                },
                "diffs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CompareDiffItem"
                    }
                },
                "message": {
                    "type": "string"
                },
                "version1": {
                    "$ref": "#/definitions/dto.CalculationResult"
                },
                "version2": {
                    "$ref": "#/definitions/dto.CalculationResult"
                }
            }
        },
        "dto.CompareSummary": {
            "type": "object",
            "properties": {
                "changed_fields": {
                    "description": "有变化的字段数",
                    "type": "integer"
                },
                "decreased_fields": {
                    "description": "减少的字段数",
                    "type": "integer"
                },
                "increased_fields": {
                    "description": "增加的字段数",
                    "type": "integer"
                },
                "total_fields": {
                    "description": "总字段数",
                    "type": "integer"
                }
            }
        },
        "dto.HistoryDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.CalculationResult"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.HistoryItem": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "crowd": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "nutrient_name": {
                    "type": "string"
                },
                "scenario": {
                    "type": "string"
                },
                "target_median": {
                    "type": "number"
                },
                "unit": {
                    "type": "string"
                },
                "version_id": {
                    "type": "string"
                }
            }
        },
        "dto.HistoryListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.HistoryItem"
                    }
                },
                "message": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.TargetData": {
            "type": "object",
            "properties": {
                "adjustment_factor": {
                    "description": "调整因子",
                    "type": "number"
                },
                "exceed_ul": {
                    "description": "是否超过UL",
                    "type": "boolean"
                },
                "nutrient_name": {
                    "type": "string"
                },
                "original_cv": {
                    "description": "原始变异系数",
                    "type": "number"
                },
                "original_mean": {
                    "description": "原始平均摄入量",
                    "type": "number"
                },
                "target_median": {
                    "description": "目标中位数",
                    "type": "number"
                },
                "target_p95": {
                    "description": "目标P95值",
                    "type": "number"
                },
                "ul": {
                    "description": "UL值",
                    "type": "number"
                },
                "unit": {
                    "description": "单位",
                    "type": "string"
                },
                "warning": {
                    "description": "警告信息",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "营养素目标计算器API",
	Description:      "基于数据库摄入数据和DRIs计算营养素目标摄入量的API，支持Redis缓存、历史记录查询和版本对比",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
