// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/target/calculate": {
            "post": {
                "description": "根据人群特征、营养素名称和场景，计算目标中位数并检查P95是否超UL。计算结果会自动保存到Redis，TTL=1天",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "营养素目标计算"
                ],
                "summary": "计算营养素目标摄入量",
                "parameters": [
                    {
                        "description": "计算请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CalculateTargetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回计算结果",
                        "schema": {
                            "$ref": "#/definitions/dto.CalculateTargetResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/target/history": {
            "get": {
                "description": "获取指定用户的计算历史记录列表，按时间倒序排列",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "历史记录"
                ],
                "summary": "获取用户历史记录列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "返回数量限制，默认10",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回历史记录列表",
                        "schema": {
                            "$ref": "#/definitions/dto.HistoryListResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "根据 Redis Key 删除指定的历史记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "历史记录"
                ],
                "summary": "删除历史记录",
                "parameters": [
                    {
                        "description": "删除请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteHistoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/target/history/compare": {
            "post": {
                "description": "对比两个历史计算记录的差异，返回详细的字段对比信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "历史记录"
                ],
                "summary": "对比两个历史版本",
                "parameters": [
                    {
                        "description": "对比请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CompareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回对比结果",
                        "schema": {
                            "$ref": "#/definitions/dto.CompareResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "记录不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/target/history/detail": {
            "get": {
                "description": "根据 Redis Key 获取单条历史记录的完整详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "历史记录"
                ],
                "summary": "获取历史记录详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Redis Key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回历史记录详情",
                        "schema": {
                            "$ref": "#/definitions/dto.HistoryDetailResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "记录不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CalculateTargetRequest": {
            "type": "object",
            "required": [
                "age",
                "crowd",
                "gender",
                "nutrient_name",
                "scenario"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "maximum": 120,
                    "minimum": 0,
                    "example": 30
                },
                "crowd": {
                    "type": "string",
                    "example": "普通人群"
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "男",
                        "女"
                    ],
                    "example": "男"
                },
                "nutrient_name": {
                    "type": "string",
                    "example": "维生素C"
                },
                "scenario": {
                    "type": "string",
                    "enum": [
                        "A",
                        "B",
                        "C"
                    ],
                    "example": "A"
                }
            }
        },
        "dto.CalculateTargetResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.TargetData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.CalculationRecord": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "格式化时间",
                    "type": "string"
                },
                "id": {
                    "description": "记录ID (UUID)",
                    "type": "string"
                },
                "request": {
                    "description": "请求参数",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.CalculateTargetRequest"
                        }
                    ]
                },
                "result": {
                    "description": "计算结果",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.TargetData"
                        }
                    ]
                },
                "timestamp": {
                    "description": "计算时间戳",
                    "type": "integer"
                },
                "ttl_seconds": {
                    "description": "剩余过期时间（秒）",
                    "type": "integer",
                    "example": 86400
                },
                "user_id": {
                    "description": "用户ID",
                    "type": "string"
                }
            }
        },
        "dto.CompareData": {
            "type": "object",
            "properties": {
                "differences": {
                    "description": "差异项列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DifferenceItem"
                    }
                },
                "record1": {
                    "description": "第一个记录",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.CalculationRecord"
                        }
                    ]
                },
                "record2": {
                    "description": "第二个记录",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.CalculationRecord"
                        }
                    ]
                },
                "summary": {
                    "description": "对比摘要",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.CompareSummary"
                        }
                    ]
                }
            }
        },
        "dto.CompareRequest": {
            "type": "object",
            "required": [
                "key1",
                "key2"
            ],
            "properties": {
                "key1": {
                    "description": "第一个版本Key",
                    "type": "string",
                    "example": "calc:user123:1710900000:abc123"
                },
                "key2": {
                    "description": "第二个版本Key",
                    "type": "string",
                    "example": "calc:user123:1710900100:def456"
                }
            }
        },
        "dto.CompareResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.CompareData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.CompareSummary": {
            "type": "object",
            "properties": {
                "changed_fields": {
                    "description": "变化字段数",
                    "type": "integer"
                },
                "decreased_count": {
                    "description": "减少数量",
                    "type": "integer"
                },
                "increased_count": {
                    "description": "增加数量",
                    "type": "integer"
                },
                "main_change": {
                    "description": "主要变化描述",
                    "type": "string"
                },
                "total_fields": {
                    "description": "总字段数",
                    "type": "integer"
                }
            }
        },
        "dto.DeleteHistoryRequest": {
            "type": "object",
            "required": [
                "key"
            ],
            "properties": {
                "key": {
                    "description": "Redis Key",
                    "type": "string",
                    "example": "calc:user123:1710900000:abc123"
                }
            }
        },
        "dto.DeleteHistoryResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.DifferenceItem": {
            "type": "object",
            "properties": {
                "change_percent": {
                    "description": "变化百分比（数值型）",
                    "type": "number"
                },
                "change_type": {
                    "description": "变化类型: increased, decreased, unchanged",
                    "type": "string"
                },
                "field": {
                    "description": "字段名",
                    "type": "string"
                },
                "field_name": {
                    "description": "字段中文名",
                    "type": "string"
                },
                "new_value": {
                    "description": "新值"
                },
                "old_value": {
                    "description": "旧值"
                }
            }
        },
        "dto.HistoryDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.CalculationRecord"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.HistoryListData": {
            "type": "object",
            "properties": {
                "records": {
                    "description": "记录列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.HistoryRecordItem"
                    }
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "dto.HistoryListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.HistoryListData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.HistoryRecordItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "格式化时间",
                    "type": "string"
                },
                "id": {
                    "description": "记录ID",
                    "type": "string"
                },
                "key": {
                    "description": "Redis Key",
                    "type": "string"
                },
                "nutrient": {
                    "description": "营养素名称",
                    "type": "string"
                },
                "scenario": {
                    "description": "场景",
                    "type": "string"
                },
                "target_median": {
                    "description": "目标中位数",
                    "type": "number"
                },
                "timestamp": {
                    "description": "计算时间戳",
                    "type": "integer"
                },
                "unit": {
                    "description": "单位",
                    "type": "string"
                }
            }
        },
        "dto.TargetData": {
            "type": "object",
            "properties": {
                "adjustment_factor": {
                    "description": "调整因子",
                    "type": "number"
                },
                "exceed_ul": {
                    "description": "是否超过UL",
                    "type": "boolean"
                },
                "nutrient_name": {
                    "type": "string"
                },
                "original_cv": {
                    "description": "原始变异系数",
                    "type": "number"
                },
                "original_mean": {
                    "description": "原始平均摄入量",
                    "type": "number"
                },
                "target_median": {
                    "description": "目标中位数",
                    "type": "number"
                },
                "target_p95": {
                    "description": "目标P95值",
                    "type": "number"
                },
                "ul": {
                    "description": "UL值",
                    "type": "number"
                },
                "unit": {
                    "description": "单位",
                    "type": "string"
                },
                "warning": {
                    "description": "警告信息",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "营养素目标计算器API",
	Description:      "基于数据库摄入数据和DRIs计算营养素目标摄入量的API。支持计算结果自动保存到Redis，提供历史记录查询和版本对比功能。数据TTL=1天。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
